### PR TITLE
Show group to users on status page

### PR DESCRIPTION
**Pull request by Blaisorblade**
Relies on
ps-tuebingen/handin-config@cb9e0fdd7447ce2a586ea819ba6554063c7bd016.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
I'm far from proud of this code, and I tested it... once!

**Comment by Toxaris** [comment]
The code looks good to me, but I don't have time for testing it right now.

**Comment by yfcai** [comment]
Is it okay to put line breaks in `Tutoriumstermin`? Is the following fine as value of the field:

```
Zeit: Dienstag, 08.00 Uhr
Ort:  Raum VB N3, Morgenstelle
Tutor: ivan_the_terrible
```

**Comment by Blaisorblade** [comment]
> Is it okay to put line breaks in Tutoriumstermin? Is the following fine as value of the field:

Ah good to know. You go ahead, I'll change the generated HTML to still display the line breaks before merging :-)

**Comment by b-studios** [comment]
Easy way: put a `<pre>`
Correct way: replace text by a definition list

```
<dl><dt>Zeit</dt><dd>Dienstag, 08.00 Uhr</dd></dl>
...
```

**Comment by Blaisorblade** [comment]
> definition list.

No clue why a definition list. How would you format Cai's example?
My plan was to turn lines into paragraphs, or newlines into `<br />`. But I can produce any HTML you want :wink:

**Comment by b-studios** [comment]
Sorry, immediately edited my comment. See above.

**Comment by Toxaris** [comment]
Jona uses definition lists to represent lists of key-value pairs.

``` html
<dl>
<dt>Zeit</dt><dd>Dienstag, 08.00 Uhr</dd>
<dt>Ort</dt><dd>Raum VB N3, Morgenstelle</dd>
<dt>Tutor</dt><dd>ivan_the_terrible</dd>
</dl>
```

**Comment by b-studios** [comment]
@Toxaris Thanks, yes :)

**Comment by Blaisorblade** [comment]
BTW, I'm not sure where documentation for this should go (beyond this issue comments, ahem).

**Comment by yfcai** [comment]
The handin server parses the field "Tutoriumstermin". We should document the interface somewhere. Here's a preliminary description for 6173bef8916fee4c4c507168495a40a3ca862273.
- If "Tutoriumstermin" is a 3-line string such that each line has the form `<tag>: <content>`, then the field is displayed as a table. `<tag>` and `<content>` should contain no colon `:`. There should be _one_ or more spaces after the colon.
- Otherwise "Noch keine Termin zugewiesen" is displayed.

Examples

Input: "Zeit: Dienstag, 08.00 Uhr\nOrt:  Raum VB N3, Morgenstelle\nTutor: ivan_the_terrible"
Output: displayed as a table

Input: "Zeit: Dienstag, 08.00 Uhr\nOrt:  Raum VB N3, Morgenstelle\nStudierende: alice, bob, eve"
Output: displayed as a table

Input: "a:b\nc:d\ne:f\ng:h"
Output: "Noch keine Termin zugewiesen"

**Comment by yfcai** [comment]
The perfect future treatment would be that the handin server formats the string in "Tutoriumstermin" according to some simple scheme, and the Discourse database keeps the responsibility for what to display for people without assignments.

A perfect display scheme is markdown. For starters (in case someone still wants to work on this), the handin server could blindly format "Tutoriumstermin" as a table denoted by some nullable tab-separated values. This way, all strings are displayed in some way and future users have the freedom to add/remove rows/columns.

**Comment by Blaisorblade** [comment]
> The perfect future treatment

This is interesting, but we're shipping in a couple of days :wink:, so we don't have time to design and debug major changes. Technical debt is already growing fast and I don't want to ship a nest of bugs.

I agree that what we implemented here isn't fully general, and what you propose is more elegant in some sense. But I don't think we know fully general requirements, so this sounds like a case of YAGNI ("You aren't gonna need it"): designing something overly general without enough info, so that later you actually need _different_ generality which is incompatible with what you have and end up rewriting it anyway.

> Markdown

Even if there were a Racket library for that, that seems way overkill.

> For starters (in case someone still wants to work on this), the handin server could blindly format "Tutoriumstermin" as a nullable ;-separated values (i. e., the European CSV). This way, all strings are displayed in some way and future users have the freedom to add/remove rows/columns.

I won't deploy an incompatible interface change (semicolon instead of colon) a couple of days before shipping.

I can trivially remove the requirement of having 3 rows, and trust the the scheduler behaves properly — I put it there because the "spec" I had boiled down to "either 3x2 CSV with colons, or kind-of arbitrary other stuff".
But the display format we're using (definition lists) doesn't work with more columns.

**Comment by yfcai** [comment]
I agree with leaving it as-is for this year; I just have a bad feeling about having to document this field at all.

**Pull request merged**
