### PR TITLE
Language definitions for template files, with correct usage example

### PR DESCRIPTION
**Pull request by Blaisorblade**
This PR should have the correct interface for clients of these languages.

And hopefully this part is otherwise ready for merging.

In turn, merging this PR will enable testing changes to the other repo in the correct setup (we've already seen that this appears to work, I'd still like to confirm that).

### CODE REVIEW

**Comment by Blaisorblade** [comment]
> I think these comments should be addressed by now — we're certainly not using error any more :-).

Even though we use `raise-syntax-error`, we don't show source locations apparently.

This is not a blocker for the PR (viceversa, leaving this PR unmerged is a blocker for lots of testing), but it'd be nice to fix this before the demo to tutors.

**Comment by lordxist** [comment]
> Even though we use raise-syntax-error, we don't show source locations apparently.

Right, didn't get to that yet. Shall we first merge this PR, and I then (hopefully) improve on the `raise-syntax-error` before the weekend and open another PR?

**Comment by Blaisorblade** [comment]
> Shall we first merge this PR,
> We should first merge this PR — I have one thing I'd like to get reviewed before merging.

Specifically: @Toxaris, I'd like to check the _interface_ between this code and the users. Currently template files use 

```
#lang s-exp utue-info1-lang-def/grade-template-lang
```

because I tried to make the [_collection name_](https://docs.racket-lang.org/guide/module-basics.html#%28tech._collection%29) `utue-info1-lang-def` reasonably unique (but decided against putting the semester in). Since that line is an interface with the tutors who'll use our script, we should get that right. Is that line fine?

>  and I then (hopefully) improve on the raise-syntax-error before the weekend and open another PR?

I have some changes on `raise-syntax-error` to add source locations, maybe I'll merge them in here; some are probably better separated.

**Comment by lordxist** [comment]
> Since that line is an interface with the tutors who'll use our script, we should get that right.

Maybe I misunderstand something here, but do the tutors need to look at the template? I thought they used the generated `grade-prefilled` files?

**Comment by Blaisorblade** [comment]
> Maybe I misunderstand something here, but do the tutors need to look at the template? I thought they used the generated grade-prefilled files?

You're right. Still, the `grade-prefilled.rktd` depend on `grade-template.rktd` which therefore should be on their computer, and I'm trying to avoid updating `grade-template.rktd`.

In fact, having them _download_ `grade-template.rktd` at all is a new step, I have some ideas on simplifying that.

**Comment by Toxaris** [comment]
> Currently template files use `#lang s-exp utue-info1-lang-def/grade-template-lang` because I tried to make the collection name `utue-info1-lang-def` reasonably unique

Why? Maybe I'm wrong, but it seems that there's nothing Tübingen oder Info 1-specific about these files.

**Comment by Blaisorblade** [comment]
> Why? Maybe I'm wrong, but it seems that there's nothing Tübingen oder Info 1-specific about these files.

In fact, I was afraid the name wasn't specific enough and would cause trouble, and that's why I asked.

My concern is rather conservative: I was afraid of making the collection name `lang-def` unavailable for tutors, by just assuming that no tutor will try using a package with that collection name.

That suggests: probably in the long run we want a better name, but unless you have a good proposal, I wouldn't want to hold testing while we figure out a good name.

But to hit next week's release date, I'm fine with a name that won't create deployment conflicts and that makes sense to tutors.

**Comment by Toxaris** [comment]
I see. Well, `lang-def` is indeed not the best name :)

What about `#lang sexp handin/grade-template`?

**Comment by Blaisorblade** [comment]
Discussion on Slack setted on `handin-server/grade-template`, which could be provided in this repo or not.

**Pull request merged**
