### PR TITLE
GUI improvements

### PR DESCRIPTION
**Pull request by Blaisorblade**
Needs retesting before merge.

Fix ps-tuebingen/info1-teaching-material#7.
Fix ps-tuebingen/info1-teaching-material#49.

To do that, I changed the handin client:
- [x] disable controls for interrupting submission
- [x] show warnings asynchronously without changing the protocol (through a horrible hack, I'll admit).
- [x] show whether the solution is saved at the beginning of the checker message, beyond the status line, as asked here https://github.com/ps-tuebingen/info1-teaching-material/issues/42#issuecomment-152862593

### CODE REVIEW

**Comment by Blaisorblade** [comment]
OK, I just got a better idea :smile:

**Comment by Blaisorblade** [comment]
The only remaining problem is that the final message is still in English, and is used both in the status bar (surrounded by an English interface) and in the warning box (followed by German text), and we need something more clever there — maybe just translate the GUI?
A moment ago you got this language mixture:

```
Handin successful.
Leider haben wir ein Problem gefunden, als wir versucht haben, Ihre Abgabe auszuprobieren.

Achtung: Leider können wir Ihre Abgabe nicht akzeptieren, weil Sie haben die falsche Sprache ausgewählt.
Auf dem Aufgabenblatt ist angegeben welche Sprache die richtige für diese Abgabe ist.

Bitte wählen Sie entsprechende Sprache aus und reichen Sie dann nochmals ein.--------

Den vollständigen Bericht über das Problem, das wir gefunden haben, finden Sie auch auf dem Abgabenserver.
```

After 74703b3468549c474a79b533c5182e198f1ceed0, the first line became "Erfolgreiche Abgabe!", only in that box, but I'm not proud of that.

**Comment by Toxaris** [comment]
"Erfolgreiche Abgabe" and "Achtung: Leider können wir Ihre Abgabe nicht akzeptieren" don't make sense together, so this **does not** seem to adress https://github.com/ps-tuebingen/info1-teaching-material/issues/42#issuecomment-152862593 currently.

**Comment by Toxaris** [comment]
So with these changes, the process is as follows, correct?
- server sends multi-line warnings
- client stores multi-line warnings
- server stores handin.rkt
- server sends single-line final message
- client displays final message and warnings in a message box

At some point, we also talked about the following:
- server stores handin.rkt
- server sends multi-line (!) final message
- client displays final message in a multi-line version of the status line

What happened to this idea of putting all the text into the final message and tweaking the client GUI to have room for a multi-line final message?

**Comment by Blaisorblade** [comment]
> "Erfolgreiche Abgabe" and "Achtung: Leider können wir Ihre Abgabe nicht akzeptieren" don't make sense together, so this does not seem to adress ps-tuebingen/info1-teaching-material#42 (comment) currently.

Problem is, I can only get the logic right, not the text.
This change fixes the logic, so at most somebody still needs to drop "Achtung: Leider können wir Ihre Abgabe nicht akzeptieren". See 89a6811f765881b05064f8c8a5fb93db49125114; I'm leaving translation to you, and assigned you the issue.

> So with these changes, the process is as follows, correct?

Yep. (Except that "Handin successful" is not sent but inferred, _once the connection completes as expected_, but most of the times it doesn't make a difference).

> At some point, we also talked about the following:
> 
> server stores handin.rkt
> server sends multi-line (!) final message
> client displays final message in a multi-line version of the status line
> What happened to this idea of putting all the text into the final message and tweaking the client GUI to have room for a multi-line final message?

That'd be simpler and cleaner, and if we managed to force an update, we might be able to do that. So it is certainly an option, and I'd like to do that _at the end of the course_.

But current clients will not handle that very gracefully, because in practice that's an incompatible protocol change (though a somewhat trivial one). They'll try to put the message in the status line. If the message is longer than 200 characters, that'll violate the documented contract, so DrRacket will show a stacktrace. IIRC, DrRacket will resume operations normally, but users will be confused and probably won't see the warning.

We could conceivably update clients now and update server behavior in X weeks, or something else, but I'd like to fix these bugs now, not in a week.

Alternatively, at some extra cost, we could update clients to support both variants of the protocol now, so that they get the fix, update the server in some weeks, and then update the clients to only support the new protocol. But the only advantage is that we avoid having a TODOs to fix in six months.

**Comment by Toxaris** [comment]
Ok I see. So the problem is that even though we invested time in auto-update, we cannot do a **forced** auto-update ;)

**Comment by Toxaris** [comment]
Well, when I wrote my comment, I didn't know whether the logic or the text was wrong.

**Comment by Blaisorblade** [comment]
> Ok I see. So the problem is that even though we invested time in auto-update, we cannot actually auto-update ;)

We can autoupdate, we just can't change the protocol easily, as far as I know. I didn't have time to check whether there's a version number somewhere in the protocol, which would change things.

**Comment by Blaisorblade** [comment]
Splitting this PR.

**Pull request closed without merging**
