### PR TITLE
Support discourse authentification

### PR DESCRIPTION
**Pull request by Toxaris**
If a user is not found in users.rktd, we talk to a Discourse instance to authenticate the user and fetch the extra-fields.

I don't know how the "register new users" and "change user data" features of the handin-client interact with this. Best disable them.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Thanks, will review soon.

> I don't know how the "register new users" and "change user data" features of the handin-client interact with this. Best disable them.

That's a bit annoying for testing. Let's include (only for local usage, for security) a `test` user with `test` password.
(An option to save the password on the client side would avoid the need for this, but that's a separate discussion).

**Comment by Toxaris** [comment]
You can create an arbitrary `users.rktd` by hand, using a text editor. For example, this should work:

```
((test ((plaintext "test") "test@example.com")))
```

The format of the file is documented there: http://pkg-build.racket-lang.org/doc/handin-server/server-setup.html

**Comment by Blaisorblade** [comment]
> You can create an arbitrary users.rktd by hand, using a text editor

Sure, just want to commit and document that, for local usage only.

**Comment by Blaisorblade** [comment]
Merging:
- I've reviewed the code, it also makes enough sense (though I didn't review all details).
- After testing, I've improved handling of bad usernames.
- It now works well enough for me.

**Comment by Toxaris** [comment]
Missing feature (?): For the test instance, students should not be able to login. Instead, tutors and employees should. Needs change of the API endpoint.

**Comment by Blaisorblade** [comment]
My current hack was to create a normal user — which also showed me the forum "as users see it".
The change looks easy for a rubyist, so I'd leave this to Jona.

Relevant code is `reject { |u| u.staff? }` at https://github.com/b-studios/discourse-course/blob/master/app/controllers/course/api_controller.rb#L24 (`reject` means `filterNot`), 
I think one could just replace `u.staff?` with the Ruby for `u.staff? XOR toBoolean(params[:staff], :default => false)`.

**Comment by Blaisorblade** [comment]
@b-studios can you look at https://github.com/ps-tuebingen/handin/pull/5#issuecomment-144680521 and my answer?

**Comment by Blaisorblade** [comment]
We specified the API with @b-studios.
We add a boolean `staff` parameter to the `dump` endpoint, with possible values `true` and `false` and defaulting to `false` (so the default keeps the current behavior).

**Comment by Toxaris** [comment]
Cool. @Blaisorblade, can you change the handin-server to read the `staff` parameter from a configuration file, so that we can configure it differently on the staging and production instances?

**Comment by b-studios** [comment]
The plugin apparently is not autoupdated at the running discourse instance (at least not so far). @Blaisorblade can you check that? My approach would be to restart the forum -- but I know you do not like that.

**Comment by Blaisorblade** [comment]
The interface is at https://forum-ps.informatik.uni-tuebingen.de/admin/upgrade, you gotta trigger the upgrade manually. And there's no way to find that URL from the admin interface, apparently :-1: :cry:

**Comment by Blaisorblade** [comment]
> Cool. @Blaisorblade, can you change the handin-server to read the staff parameter from a configuration file, so that we can configure it differently on the staging and production instances?

That's my plan :smile:

**Comment by Blaisorblade** [comment]
The field name: `discourse-auth-staff`, in `config.rktd` (since the discourse config is not part of branches), a boolean. I'm setting it up ASAP.

**Comment by Toxaris** [comment]
About the magic URL we need to remember: We could put it into a thread in some private section of the forum.

**Comment by Blaisorblade** [comment]
> About the magic URL we need to remember: We could put it into a thread in some private section of the forum.

https://forum-ps.informatik.uni-tuebingen.de/t/howto-upgrading-discourse-and-or-plugins/122

**Comment by b-studios** [comment]
Ok, now that the plugin is updated the new output can be inspected at
https://forum-ps.informatik.uni-tuebingen.de/admin/course/dump.json?staff=true

**Comment by Blaisorblade** [comment]
:+1: Great!

**Comment by Blaisorblade** [comment]
I just fixed staff handling and case-sensitivity on the Racket side.

**Comment by Toxaris** [comment]
@Blaisorblade wrote:

> Let's include (only for local usage, for security) a test user with test password.

Did we ever do this?

**Comment by Blaisorblade** [comment]
> @Blaisorblade wrote:
> 
> Let's include (only for local usage, for security) a test user with test password.
> Did we ever do this?

I provided a sample file for that. Copy [users.rktd.sample](https://github.com/ps-tuebingen/handin-config/blob/master/users.rktd.sample) to users.rktd and you're golden*!

*Unless somebody updated extra-fields without updating that entry — some new code of mine will just explode then :cry:

**Comment by Toxaris** [comment]
:+1: Oh didn't see the sampe file. thanks.

**Pull request merged**
