### PR TITLE
Disable "manage client" menu

### PR DESCRIPTION
**Pull request by Blaisorblade**

### CODE REVIEW

**Comment by Blaisorblade** [comment]
(Well, untested yet...)

**Comment by Blaisorblade** [comment]
I just learned that, hidden in this dialog, there's the "uninstall" function — which is pretty much the only way to uninstall the plugin O_O.

**Comment by Toxaris** [comment]
Shouldn't the "Paketmanager" work too.

**Comment by Blaisorblade** [comment]
> Shouldn't the "Paketmanager" work too.

Unfortunately no, it doesn't, and that's by (strange) design, because these are .plt files (Planet archives) and not packages. The packages manager is just for packages — what you can manipulate with `raco pkg`. (I'm only using `.plt` files because I didn't implement autoupdate for packages).

Up to now, I only uninstalled clients through `rm -rf ~/Library/Racket/6.2.1/`, or by upgrading DrRacket :wink: .

**Pull request merged**
